### ISSUE TITLE
Midi file length issue

### ISSUE THREAD

**Issue by HeathClose** [WrongPeople/WrongPeopleVCV#2]
I think I found a bug where the midi player doesn't recognize the end of a midi clip if there isn't note information all the way to the end.  I have attached the same melody with two different midi clips, one the midi player thinks is 7 seconds, the other it thinks it's 8 seconds.  Both should be 8 seconds, but since that last note ends before the end of the loop, the midi player is truncating the clip.

[Midi Melody.mid.txt](https://github.com/WrongPeople/WrongPeopleVCV/files/3512277/Midi.Melody.mid.txt)
[Midi Melody2.mid.txt](https://github.com/WrongPeople/WrongPeopleVCV/files/3512278/Midi.Melody2.mid.txt)

**Comment by WrongPeople** [comment]
The last note-off message and the end-of-track message has the same time (7.5 seconds in first file).
You can open your file in another program (e.g. [MidiEditor](https://github.com/markusschwenk/midieditor/releases/) or [Reaper](https://www.reaper.fm/download.php)) and make sure its duration is 7.5 seconds.
MIDIPlayer displays only integer part of seconds (it will be fixed in next release), but it plays the file correctly.

[Midi.Melody3.mid.txt](https://github.com/WrongPeople/WrongPeopleVCV/files/3512509/Midi.Melody3.mid.txt)
